indent = 4
margin = 92
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = false
pipe_to_function_call = false
short_to_long_function_def = false
long_to_short_function_def = false
always_use_return = true
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = true
format_docstrings = true
conditional_to_if = true
normalize_line_endings = "unix"
trailing_comma = true
join_lines_based_on_source = true
indent_submodule = true
separate_kwargs_with_semicolon = true
surround_whereop_typeparameters = true
overwrite = true
verbose = true
format_markdown = true
align_struct_field = true
align_pair_arrow = true
